### ISSUE TITLE
Can I use these methods, or not implemented yet?

### ISSUE THREAD

**Issue by palinko91** [matinkaboli/stellar-sdk#9]
Hello! I really like this Stellar SDK, most of the others I found is not maintained and I'm happy this works like the JavaScript version, helps a lot if we are trying to migrate Javascript code!

But I would need to use these methods now:

- StellarSdk.Operation.payment
- StellarSdk.TransactionBuilder
- fetchTimebounds
- .addOperation
- .addMemo
- .submitTransaction
- transaction.sign

So basically to complete a payment and similar basic operations.

After the first review it feels like these not implemented yet. Am I right? Or I'm really overlooked something and it's possible to do this, just the methods a bit differently named like in the javascript library?

For example I haven't found  `.fetchBaseFee()` also but I was able to bypass with `.fee_stats()` then reaching the `ee_stats.last_ledger_base_fee`. Maybe the transaction building works also just not obvious for me :)

**Comment by amovah** [comment]
Hi, unfortunately they are not implemented yet.

**Comment by palinko91** [comment]
Thank you for the answer. I will try to use stellar-horizon then maybe I can solve with that but later I would be happy to help with the implementation. It would be great to have an actively maintained crate :-)

**Comment by bjorn** [comment]
> It would be great to have an actively maintained crate :-)

@palinko91 I've recently picked up maintenance of [`stellar-base`](https://github.com/aurora-rs/stellar-base-rs), [`stellar-horizon`](https://github.com/aurora-rs/stellar-horizon-rs) and some related crates since I needed to interface with Horizon for my own project, [Raccoin](https://raccoin.org/). Today I made new releases, mostly to publish the work already done by @salessandri last year.

@amovah @matinkaboli Now that I discovered this crate, I wonder a little, is it different enough from `stellar-horizon` that it makes sense to maintain both of them?

Given the shared interest in talking to Horizon and working with Stellar in general, it would be nice if we could share the effort of maintaining these libraries.
